apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                [
                  "/bin/sh",
                  "-c",
                  "date; echo Hello from the Kubernetes cluster",
                ]
          restartPolicy: Never
